SUDO=sudo
DIR=r
CMD=uname -a
FROM=/etc/debian_version
TO=/tmp
RSYNC_OPTIONS=-v
PKGS=gcc,clang,libc6-dev,make
ARCH=armhf
SUITE=stretch
MIRROR='http://mirrordirector.raspbian.org/raspbian'
SOURCESLIST='deb http://mirrordirector.raspbian.org/raspbian/ stretch main contrib non-free rpi'
BINDEPS_PKGS=debootstrap binfmt-support qemu-user-static
BINDEPS_BIN=/usr/sbin/qemu-debootstrap

$(DIR)/chroot-done: $(BINDEPS_BIN)
	[ -n "$(PKGS)" ] && INCLUDE_PKGS="--include=$(PKGS)"
	$(SUDO) ./$< \
		--variant=minbase
		-i $(PKGS) \
		--arch=$(ARCH) \
		$(SUITE) \
		$(DIR) \
		$(MIRROR) \

bindeps:
	apt-get install -q -y $(BINDEPS_PKGS)

enter: $(DIR)/chroot-done
	-$(SUDO) chroot $(DIR)
exec: $(DIR)/chroot-done
	-$(SUDO) chroot $(DIR) $(CMD)
sync:
	mkdir -p $(DIR)
	rsync -aH $(RSYNC_OPTIONS) $(FROM) $(DIR)/$(TO)
mount:
	$(SUDO) mount --bind /sys $(DIR)/sys
	$(SUDO) mount --bind /dev $(DIR)/dev
	$(SUDO) mount --bind /proc $(DIR)/proc
umount: 
	$(SUDO) umount -l $(DIR)/sys
	$(SUDO) umount -l $(DIR)/dev
	$(SUDO) umount -l $(DIR)/proc
clean:
	$(SUDO) $(RM) -rf $(DIR)

.PHONY: enter exec mount umount clean
