---
os:
  - linux
  - osx
addons:
  apt:
    packages:
      - cppcheck
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    HOMEBREW_NO_AUTO_UPDATE=1 brew install cppcheck;
    fi
language: c
compiler:
  - clang
  - gcc
env:
  - TEST_PLATFORM=native
  - TEST_PLATFORM=qemu-raspbian
sudo: required
script:
  - set -e
  - printenv
  - make lint
  - make test
matrix:
  exclude:
    - os: osx
      env: TEST_PLATFORM=qemu-raspbian
    - compiler: clang
      env: TEST_PLATFORM=qemu-raspbian
