---
os:
  - linux
  - osx
addons:
  apt:
    packages:
      - cppcheck
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    HOMEBREW_NO_AUTO_UPDATE=1 brew install cppcheck;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]] && [[ "$CC" == "gcc" ]]; then
    HOMEBREW_NO_AUTO_UPDATE=1 brew install gcc ;
    CC="/usr/local/Cellar/gcc/*/bin/gcc-?" ;
    fi
language: c
compiler:
  - clang
  - gcc
env:
  - TEST_PLATFORM=native
  - TEST_PLATFORM=qemu-user-raspbian
script:
  - set -e
  - make lint
  - make test
matrix:
  exclude:
    - os: osx
      env: TEST_PLATFORM=qemu-user-raspbian
